# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Dispatch-TextTable
version:      0.02
version_from: lib/Log/Dispatch/TextTable.pm
installdirs:  site
requires:
    Log::Dispatch:                 2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
